name: Parking Pamplona Fetcher

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  fetch-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Modify openssl.cnf
        run: |
          echo "Options = UnsafeLegacyRenegotiation" | sudo tee -a /etc/ssl/openssl.cnf

      - name: openssl version
        run: openssl version

      - name: View openssl.cnf
        run: tail /etc/ssl/openssl.cnf
        
      - name: Create Data Directory
        run: mkdir -p data/parkings/$(date +'%Y-%m')
        
      - name: Fetch XML
        run: wget -O data/parkings/$(date +'%Y-%m')/parkings_$(date +'%Y-%m-%d-%H-%M').xml https://parkings.pamplona.es/parkings.xml

      - name: Configure Git
        run: |
          git config --global user.email "alberto.labarga@gmail.com"
          git config --global user.name "Alberto Labarga"

      - name: Commit and Push
        run: |
          git add data/parkings/$(date +'%Y-%m')/parkings_$(date +'%Y-%m-%d-%H-%M').xml
          git commit -m "Add JSON file for $(date +'%Y-%m-%d %H:%M')"
          git push        
