name: Parking Pamplona Fetcher

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  fetch-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch XML
        run: wget -O data/parkings/$(date +'%Y-%m')/parkings_$(date +'%Y-%m-%d-%H-%M').xml https://parkings.pamplona.es/parkings.xml

