name: Parking Pamplona Fetcher

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every 5 minutes

jobs:
  fetch-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch XML
        run: wget -O data/bicing/$(date +'%Y-%m')/bicing_$(date +'%Y-%m-%d-%H-%M').json https://opendata-ajuntament.barcelona.cat/data/dataset/bd2462df-6e1e-4e37-8205-a4b8e7313b84/resource/e5adca8d-98bf-42c3-9b9c-364ef0a80494/download

